### ISSUE TITLE
update ionic app-scripts

### ISSUE THREAD

**Issue by dylanvdmerwe** [doo/scanbot-sdk-example-ionic#23]
Please update to latest ionic app-scripts dev package. 

`"@ionic/app-scripts": "3.2.2",`

**Comment by softcomsas** [comment]
Please update to latest ionic app-scripts dev package.

**Comment by eddyfrank** [comment]
The example project was upgraded to Ionic 4 with the latest build tools as well as the latest Cordova platforms (`cordova-android@8.0.0`, `cordova-ios@5.0.0`).
