### ISSUE TITLE
App is compiling without errors but I can only see white page in phone

### ISSUE THREAD

**Issue by obsd** [doo/scanbot-sdk-example-ionic#24]
App is compiling without errors but I can only see wight page in phone.
With ionic lab I can see the UI but on my phone white screen only.

**Comment by eddyfrank** [comment]
@obsd 
Are we talking about Android or iOS?
Please make sure you have properly done all installation steps from the README of this repo.
E.g. for iOS `ionic cordova prepare ios` is important before running the app in Xcode.

**Comment by eddyfrank** [comment]
We haven't received any updates on this issue and are assuming that this is solved.
